// Test catalogue built from Meditech Laboratory's requisition sheet.
// "note" = general, widely accepted guidance only. Always follow the lab's/doctor's instructions.
const CATEGORIES = [
{id:"haem",name:"Haematology & Blood Group",icon:"🩸",about:"Blood cells, clotting and inherited blood disorders.",tests:["CBC (Complete Blood Count)","Reticulocyte Count","ESR","Blood Group","G6PD","Sickle Cell","Hb Electrophoresis","Bleeding Time","Clotting Time","PT + INR","APTT"]},
{id:"clin",name:"Urine, Stool & Semen",icon:"🧪",about:"Routine examination and culture of body fluids and samples.",note:"Use the clean container supplied by the lab. For culture, collect before starting antibiotics unless your doctor says otherwise.",tests:["Urine Routine / Culture","Stool Routine / Culture","Semen Routine / Culture","Urine Albumin : Creatinine Ratio","Urine Protein : Creatinine Ratio"]},
{id:"diab",name:"Diabetes",icon:"🍬",about:"Blood sugar control and insulin function.",note:"Fasting glucose usually needs an 8–12 hour fast (water is allowed). Post-prandial (PP) is taken about 2 hours after a meal.",tests:["Glucose – Fasting / PP / Random","Glycosylated Hb (HbA1c)","Glucose Tolerance Test (GTT)","Insulin – Fasting / PP / Antibodies","C-Peptide"]},
{id:"lipid",name:"Lipid Profile (Heart Risk)",icon:"❤️",about:"Cholesterol and fats in the blood, used to assess cardiovascular risk.",note:"A 9–12 hour fast is commonly advised. Confirm with the lab when booking.",tests:["Lipid Profile","Cholesterol","Triglycerides","HDL, LDL, VLDL"]},
{id:"liver",name:"Liver Function Tests",icon:"🫀",about:"Shows how well the liver is working.",tests:["Liver Function Tests (LFT)","Bilirubin – Total & Direct","SGOT (AST)","SGPT (ALT)","Gamma GT","Alkaline Phosphatase"]},
{id:"kidney",name:"Kidney, Electrolytes & Minerals",icon:"💧",about:"Kidney function, salts and minerals.",tests:["Renal Function Tests (RFT)","Urea (BUN)","Creatinine","Uric Acid","Electrolytes (Na, K, Cl, iCa)","Total Protein","Albumin","Calcium","Phosphorus"]},
{id:"fever",name:"Fever & Tropical Infections",icon:"🌡️",about:"Tests commonly ordered for fever of unclear cause.",tests:["Widal Slide","Typhi Card","MP Slide (Malaria Parasite)","MP Antigen (Malaria)","Dengue Ag + Ab","Leptospira","Chikungunya"]},
{id:"sero",name:"Infection Screening & TB",icon:"🛡️",about:"Serology and tuberculosis tests.",tests:["3H Screen (HIV, HBsAg, HCV)","VDRL","HCG – Urine Pregnancy","Mantoux Test (TT)","TB Gold (IGRA)"]},
{id:"imm",name:"Immunology & Allergy",icon:"🔬",about:"Inflammation, autoimmune markers and allergy.",tests:["CRP","RA / Rh Factor","ASO","Anti-CCP","ANA","HLA B27","IgE","Allergy – Food / Drugs / Inhalation / Contact"]},
{id:"enz",name:"Cardiac Markers & Enzymes",icon:"⚡",about:"Heart, muscle and pancreatic markers.",note:"Chest pain, breathlessness or sweating is an emergency. Go to the nearest hospital; do not wait for a lab report.",tests:["Troponin T / I","CK-MB","CPK","LDH","Amylase","Lipase","Homocysteine"]},
{id:"thy",name:"Thyroid",icon:"🦋",about:"Thyroid hormones and thyroid antibodies.",tests:["TSH","T3, T4, TSH","FT3, FT4, TSH","ATPO / ATG","Thyroglobulin Level"]},
{id:"horm",name:"Hormones & Fertility",icon:"⚗️",about:"Reproductive and stress hormones.",note:"Some hormones depend on the day of the cycle or time of day (e.g. Cortisol AM / PM). Ask the lab when to come.",tests:["FSH","LH","Prolactin","Testosterone","AMH","Beta HCG","Cortisol (AM / PM)"]},
{id:"preg",name:"Pregnancy & TORCH",icon:"🤰",about:"Antenatal and infection screening during pregnancy planning.",tests:["TORCH (4 / 8)","Toxoplasma IgG / IgM","Rubella IgG / IgM","CMV IgG / IgM","HSV IgG / IgM","ANC Profile","Dual / Triple / Quad Marker"]},
{id:"vit",name:"Vitamins & Iron",icon:"🍊",about:"Nutritional status and anaemia work-up.",tests:["Vitamin B12","Vitamin D","Iron / Iron Studies","TIBC / Iron Saturation","Ferritin"]},
{id:"onco",name:"Tumour Markers",icon:"🎗️",about:"Markers used to support diagnosis and follow-up. They are not stand-alone cancer tests.",tests:["CA 19.9 (Pancreatic)","CA 15.3 (Breast)","CA 125 (Ovarian)","CA 72.4 (Gastric)","AFP","CEA","PSA – Total / Ratio"]},
{id:"path",name:"Histopathology & Cytology",icon:"🧫",about:"Tissue and cell examination under the microscope.",tests:["Histopathology","Cytology"]},
{id:"ref",name:"Referral Lab Network",icon:"🤝",about:"Special tests not done in-house are sent to partner labs.",tests:["Metropolis","Agilus","Suburban","Bhide","Medgenome"],referral:true}
];
